# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae7008c71d90b182f06afb4a3a95c44516c52a4060bba9837c6263ee63387598fe245efc27ff0daad7d9b7959df3d55923045a45df1f6cbb66007944177522f

test:
  secret_key_base: 68d957c386abfdaa7423439c204a53f78635c608279dfcf2876322b5e79b5123f6a955d72de8a31269f73c214da4e08da419175ca7fe4384c4ae3d70812195a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
